# fly.toml app configuration file generated for duo-he-shui-tg on 2025-02-12T18:08:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'duo-he-shui-tg'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
